version: '3.8'

services:
  honeypot:
    container_name: ${HONEYPOT_NAME}
    build: .
    restart: always
    ports:
      - "80:80"
      - "22:22"
      - "443:443"
      - "554:554"  # RTSP
      - "8080:8080"  # ONVIF
    environment:
      - HONEYPOT_NAME=${HONEYPOT_NAME}
      - CAMERA_MODEL=${CAMERA_MODEL}
      - HONEYPOT_IP=${HONEYPOT_IP}
      - HONEYPOT_NETMASK=${HONEYPOT_NETMASK}
      - HONEYPOT_GATEWAY=${HONEYPOT_GATEWAY}
      - HONEYPOT_MAC=${HONEYPOT_MAC}
      - HONEYPOT_DHCP=${HONEYPOT_DHCP}
      - ABUSEIPDB_API_KEY=${ABUSEIPDB_API_KEY}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./honeypot.log:/app/honeypot.log
    network_mode: "bridge"
